version: '3.3'
services:
  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    container_name: go-publisher
    ports:
      - 9001:9001
    depends_on:
      - redis
    networks:
      - microservices

  subscriber:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    container_name: go-subscriber
    ports:
      - 9002:9002
    depends_on:
      - redis
    networks:
      - microservices

  redis:
    image: redis:latest
    container_name: redis-pubsub
    ports:
      - 6379:6379
    networks:
      - microservices
    restart: unless-stopped

networks:
  microservices:
    driver: bridge