version: '3.8'
services:
  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    container_name: go-publisher
    ports:
      - "9001:9001"
    #network_mode: host
    depends_on:
      - prometheus
      - jaeger
      - redis
    networks:
      - microservices

  subscriber:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    container_name: go-subscriber
    #ports:
    #  - 9002:9002
    #network_mode: host
    depends_on:
      - redis
    networks:
      - microservices
  
  prometheus:
    image: prom/prometheus:v2.25.2
    container_name: prometheus
    ports:
      - "9090:9090"
    #volumes:
    #  - ./docs/prometheus.yml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"

  redis:
    image: redis:latest
    container_name: redis-pubsub
    ports:
      - "6380:6379"
    #network_mode: host
    networks:
      - microservices
    restart: unless-stopped

networks:
  microservices:
    driver: bridge